development:
  adapter: sqlite3
  database: atlanta_ember_backend_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: atlanta_ember_backend_test
  pool: 5
  timeout: 5000

# Heroku will take this over anyway
# production:
#   adapter: postgresql
#   database: atlanta_ember_backend_production
#   pool: 5
#   timeout: 5000
